### ISSUE TITLE
Test Session I

### ISSUE THREAD

**Issue by TekTimmy** [joshua-holly89/star-wars#1]
1) When adding a person the  "Birth Year" is not shown after creation.
2) When selecting a person with a long name the whole UI changes position.
3) Long names break the UI:
![image](https://github.com/joshua-holly89/star-wars/assets/5830299/d44b66de-7995-42bd-aab0-94bff4c4eed7)
4) After deleting ALL persons the "add person" function does not work anymore.

**Comment by joshua-holly89** [comment]
1) Fixed
2) Qpplies only to mode side-by-side. Fixed
3) Fixed by restraining length of name when adding person
4) Can not reproduce
